# use updated version of the packages, first check which version is used in the project do not downgrade the version of the package

name: vivah_dera
description: "A venue booking app for weddings and events"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.6.5
  google_maps_flutter: ^2.10.1
  flutter_stripe: ^11.4.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  intl: ^0.20.2
  fl_chart: ^0.70.2
  table_calendar: ^3.2.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^18.0.1
  share_plus: ^10.1.4
  path_provider: ^2.1.1
  pdf: ^3.10.7

dependency_overrides:
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_windows: ^4.0.0
  freezed_annotation: ^3.0.0
  material_color_utilities: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
